### ISSUE TITLE
启动失败 sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by jsmjsm** [genelocated/telegram-find-in-channel-bot#1]
系统 CentoOS 7

操作记录：
```
root@ python3 -m tgficbot.main

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/telegram-find-in-channel-bot/tgficbot/main.py", line 9, in <module>
    from tgficbot import db, states
  File "/home/telegram-find-in-channel-bot/tgficbot/db.py", line 8, in <module>
    conn = sqlite3.connect(dbpath)
sqlite3.OperationalError: unable to open database file
```

**Comment by chuangzhu** [comment]
请问你的 Python 具体是那个版本？我用 virtualenv 试了试在 3.6.0 下运行，sqlite3 是会自动创建数据库的。

**Comment by jsmjsm** [comment]
用的是CentOS7下面的Python 3.6
后面通过自己用Sqlite3在对应路径创建数据库解决了问题。

另外

Bot是不是要自己设置后台持续运行？

**Comment by chuangzhu** [comment]
那我待会再试试在 CentOS 7 上运行。

> Bot是不是要自己设置后台持续运行？

是的，比如你可以使用一个 systemd 服务文件启动。

```sh
vim /etc/systemd/system/tgficbot.service
```

```ini
[Unit]
Description=Telegram Find in Channel Bot
After=network-online.target

[Service]
ExecStart=python3 -m tgficbot.main
WorkingDirectory=/root/.cache

[Install]
WantedBy=multi-user.target
```

```
systemctl daemon-reload
systemctl enable --now tgficbot.service
```

**Comment by chuangzhu** [comment]
我可能知道你遇到的问题了。你的系统应该是之前没有程序创建过 `~/.cache` 路径，所以无法自动创建 `~/.cache/tgficbot.db` 文件。下个版本我会加上可指定数据库文件的路径。
